/*
 * Credits (design "에셋·크레딧", task 25.2; Req 40.2, 40.3, 43.9): the libraries the game ships or is built and tested
 * with, and every bundled third-party asset (CC0-1.0 only, listed in public/assets/manifest.json). CREDITS.md at the
 * repository root holds the same lists; tests/unit/credits.test.ts keeps the two in sync, checks every manifest entry is
 * credited here as CC0-1.0, and the Title Screen's Credits screen shows this module.
 *
 * Every character, enemy, Elite, Caelith and NPC model, every texture, sound and music track of the game itself is
 * generated by code at run time; external models are swapped in only through src/data/visualManifest.ts, and each such
 * model needs an ASSET_CREDITS entry.
 *
 * Pure data.
 */

export interface LibraryCredit {
  /** npm package name. */
  readonly name: string;
  readonly version: string;
  readonly author: string;
  readonly url: string;
  /** SPDX identifier. */
  readonly license: string;
  /** Shipped in the game build, or used only to build / test it. */
  readonly use: 'runtime' | 'dev';
}

export interface AssetCredit {
  /** The manifest id (sfx_*, mus_*, or a model id). */
  readonly id: string;
  readonly name: string;
  readonly author: string;
  readonly url: string;
  /** Always CC0-1.0 for bundled assets. */
  readonly license: string;
  /** Path under public/ (or tests/fixtures/ for test-only samples). */
  readonly path: string;
}

export const LIBRARY_CREDITS: readonly LibraryCredit[] = [
  { name: 'three', version: '0.186.1', author: 'three.js authors', url: 'https://threejs.org/', license: 'MIT', use: 'runtime' },
  { name: '@pixiv/three-vrm', version: '3.5.5', author: 'pixiv Inc.', url: 'https://github.com/pixiv/three-vrm', license: 'MIT', use: 'runtime' },
  { name: 'vite', version: '8.3.1', author: 'VoidZero Inc. and Vite contributors', url: 'https://vite.dev/', license: 'MIT', use: 'dev' },
  { name: 'typescript', version: '7.0.2', author: 'Microsoft Corporation', url: 'https://www.typescriptlang.org/', license: 'Apache-2.0', use: 'dev' },
  { name: 'vitest', version: '5.0.2', author: 'Vitest contributors', url: 'https://vitest.dev/', license: 'MIT', use: 'dev' },
  { name: 'fast-check', version: '4.10.2', author: 'Nicolas Dubien', url: 'https://fast-check.dev/', license: 'MIT', use: 'dev' },
  { name: '@playwright/test', version: '1.63.0', author: 'Microsoft Corporation', url: 'https://playwright.dev/', license: 'Apache-2.0', use: 'dev' },
  { name: '@types/three', version: '0.186.0', author: 'DefinitelyTyped contributors', url: 'https://github.com/DefinitelyTyped/DefinitelyTyped', license: 'MIT', use: 'dev' },
];

/** Bundled third-party assets: none yet (every sound, model and texture is generated in code). */
export const ASSET_CREDITS: readonly AssetCredit[] = [];

/** The license accepted for bundled assets. */
export const ASSET_LICENSE = 'CC0-1.0';

/** Lines the Credits screen shows, section by section. */
export function creditSections(): readonly { readonly title: string; readonly lines: readonly string[] }[] {
  return [
    {
      title: '제작',
      lines: ['Skyshard: Echoes of the Wild', '캐릭터·적·보스 모델, 음악, 효과음은 모두 코드로 생성했습니다.'],
    },
    {
      title: '사용 라이브러리',
      lines: LIBRARY_CREDITS.map((l) => `${l.name} ${l.version} — ${l.author} (${l.license}${l.use === 'dev' ? ', 개발용' : ''})`),
    },
    {
      title: '외부 에셋 (CC0-1.0)',
      lines: ASSET_CREDITS.length === 0 ? ['외부 에셋 없음'] : ASSET_CREDITS.map((a) => `${a.name} — ${a.author} (${a.license})`),
    },
  ];
}
